title: cdblg
author: Chen Kinnrot
email: kinnrot@gmail.com
github_username: kinnrot
twitter_username: kinnrot
description: Every time I get to an obstacle while programming, I make sure to write it down, it's all here, enjoy.
theme: minima
url: https://kinnrot.hithub.io
google_analytics: UA-103259749-1

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

disqus:
  shortname: cdblg
